### ISSUE TITLE
천일택배 배송조회 관련 문의

### ISSUE THREAD

**Issue by minkyunghye** [pihitpihit/ExcelParcelTracker#1]
천일택배 조회시 최종 값이 업데이트가 안된다고 합니다 

예시송장 : -----------

배송완료 되었는데, 엑셀로  조회시   배송 중으로만 확인된다고 합니다 확인 부탁드립니다

**Comment by pihitpihit** [comment]
일단 `직접 확인하기 링크`로 수동 확인하셔야 될 것 같아요
이슈는 확인해보겠습니다 😀

**Comment by pihitpihit** [comment]
@minkyunghye 현재 이슈는 v4.3.2에서 개선되었으니 참고 부탁드립니다.
본문의 송장번호는 가림처리 했습니다. 많은 이용 바랍니다.
