### ISSUE TITLE
배송조회 택배사 추가요청(물류대장)

### ISSUE THREAD

**Issue by minkyunghye** [pihitpihit/ExcelParcelTracker#2]
안녕하세요 

배송조회 택배사 추가요청드립니다 

1.  추가요청 배송사 명 :  물류 대장 
2.  예시 송장번호

--------
--------
--------
--------

3.  물류조회 사이트 : https://lfs-body.logimate.co.kr/logistics

바쁘시겠지만,  해당 건 조회 가 될 수 있도록 부탁드립니다.

감사합니다

**Comment by pihitpihit** [comment]
@minkyunghye This issue has been resolved in [version 4.3.4](https://github.com/pihitpihit/ExcelParcelTracker/releases/tag/4.3.4). If you got a problem, please register a [new issue](https://github.com/pihitpihit/ExcelParcelTracker/issues/new/choose). Thank you ;)
